config/routes.rb
Rails.application.routes.draw do
 
  resources :categories
  devise_for :users
  # get 'main/index'
  resources :main
  resources :products
 
  root to: 'products#index'
 

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # validates :category, presence: true
    
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  
    validates :name, presence: true
    validates :price, presence: true

    belongs_to :category
    has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def new
  end

  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
    
    cate = params[:cate]
    if !cate.nil?
      @products = Product.where(:category_id => cate)
    else
      @products = Product.all
    end

  
  end

  def show
    @product = Product.find(params[:id])
 
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to @product, notice: "Product was successfully added"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy
    redirect_to :action => :index, notice: "Product was successfully destroyed."
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :category_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "products/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/new.html.erb
<h1>Main#new</h1>
<p>Find me in app/views/main/new.html.erb</p>

app/views/main/show.html.erb
<h1>Main#show</h1>
<p>Find me in app/views/main/show.html.erb</p>

app/views/products/_form.html.erb
<div class="d-flex flex-row justify-content-center">
    <div class="col-md-8">
    <div class="card mt-5">
    <div class="card-body">
    <%= simple_form_for @product do |f| %>

     <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %>
    </div>
    <br>

    <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class:"form-control" %>
    </div>
    <br>

    <div class="form-group">
        <%= f.label :category_id %>
        <%= f.select :category_id, Category.all.map {|c|[c.category, c.id]} %>
    </div>
    <br>
    
    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <br>
    <div class="actions">
        <%= f.submit 'Create Product', class:"btn btn-primary" %>
        <%= link_to "Back", products_path, class:"btn btn-primary" %>
    </div>
    <% end %>

    </div>
    </div>
    </div>
</div>

app/views/products/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Online Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item active">
          <%= link_to "Create Product", new_product_path, class: 'nav-link' %>
        </li>
          <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
             </li>
        <% else %>
           <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
       <% end %>
        
      </ul>

    
       
         
     
    </div>
  </div>
</nav>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-10">
  <div class="row">

    <% @products.each do |product| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="Card-body">
                    <h4><%= link_to product.name, product_path(product.id) %></h4>
                    <%= link_to "View", product_path(product.id), class:"btn btn-secondary" %>
                  
                </div>
            </div>
        </div>
    <% end %>
    </div>
    </div>


    <div class="col-md-2">
      <div class="card mt-3">
        <div class="card-header" >
          Categories
        </div>
    </div>

    <div class="card-body">

    <ul class="list-group">
        <% @categories.each do |category| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= link_to category.category, products_path(:cate => category.id)%>
            <span class="badge bg-primary rounded-pill"><%= category.products.count %></span>
          </li>
        <% end %>
    </ul>
        
       
        
    </div>

    
        
    

  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="container-fluid mt-3">


<h2>Category: 
    <%= @product.category %>
</h2>
<h4><%= @product.name %></h4>
<h4><%= @product.price %></h4>

<h4><%= image_tag(@product.image, style:'width:20%') %><h4>

<%= link_to "Edit", edit_product_path(@product.id), class:"btn btn-primary" %>
<%= link_to "Delete", product_path(@product.id), method: :delete, class:"btn btn-danger" %>
<%= link_to "Back", products_path, class:"btn btn-secondary" %>



</div>